require('mappings')

require('vars')
require('plugins')
require('colors')
require('luasnip')
require('vimtex')
require('statusline')
require('swarm')
require('spell')
require('asy')

require('typst')
require('cmp_config')
require('linter')
require('lsp')
require('tscope')
require('tterm')
require('banMathLazy')
require('ts')
require('undotree')
require('autopairs')

